replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/notification-service
  pullPolicy: IfNotPresent
  tag: "e54c1c52227af3696968040d5dbe25cb08ef4cb7"

service:
  type: ClusterIP
  port: 8083

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi