replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/notification-service
  pullPolicy: IfNotPresent
  tag: "f3779c204e8e618f52b20138bf4d47a782fd8d02"

service:
  type: ClusterIP
  port: 8083

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi