apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            containerPort: {{ .Values.service.port}}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credintials
                  key: mongodb-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credintials
                  key: mongodb-password
          volumeMounts:
            - name: mongodb-data
              mountpath: /data/db
          resources:
            {{- toYaml .Values.resources | nindent 12}}
  volumeClaimTemplates:
    - metadata:
		    name: mongodb-data
			spec:
			  accessModes: ["ReadWriteOnce"]
				resources:
				  request:
					  storage: {{ .Values.storage.size }}