replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/discovery-server
  pullPolicy: IfNotPresent
  tag: "69e5e4caf2cb7a29bafd8cdcf696af08401fdc04"

service: 
  type: ClusterIP
  port: 8761

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi