replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/discovery-server
  pullPolicy: IfNotPresent
  tag: "56a21774083d313e4b0916416e0f957f9db6f622"

service: 
  type: ClusterIP
  port: 8761

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi