replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/discovery-server
  pullPolicy: IfNotPresent
  tag: "febb5bbc67826a4aea9c5e4ec86153220531c666"

service: 
  type: ClusterIP
  port: 8761

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi