apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: notificationtopic
  namespace: ecommerce
  labels:
    strimzi.io/cluster: ecommerce-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824