replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/order-service
  pullPolicy: IfNotPresent
  tag: "d2a6c766ba48306ed2826944397e98c884f40beb"

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi