replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/order-service
  pullPolicy: IfNotPresent
  tag: "aaebc75c26948cf7f905c714a1a1440b42b754b7"

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi