replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/api-gateway
  pullPolicy: IfNotPresent
  tag: "2f0e7510389ad9a98ff1f2fc9410f8b7663cb5c5"

service: 
  type: ClusterIP
  port: 8181

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi