replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/api-gateway
  pullPolicy: IfNotPresent
  tag: "366578b59dfa5084ada1cfd57430ecc5c459e9cf"

service: 
  type: ClusterIP
  port: 8181

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi