image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

storage:
  size: 2Gi

service:
  port: 5432

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi