replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/inventory-service
  pullPolicy: IfNotPresent
  tag: "c0ee6af0b8f65d424ef21f509ebacf641b3f030f"

service:
  type: ClusterIP
  port: 8082

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi