replicaCount: 1

image:
  repository: 427064007409.dkr.ecr.eu-central-1.amazonaws.com/inventory-service
  pullPolicy: IfNotPresent
  tag: "9533f80d183a4cdddc40002ed6787f9952704879"

service:
  type: ClusterIP
  port: 8082

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi