name: CI - api-gateway

on:
  push:
    branches: [main]
    paths:
      - 'api-gateway/**'

concurrency:
  group: git-push-values
  cancel-in-progress: false

jobs:
  call-build:
    uses: ./.github/workflows/_reusable-build.yaml
    with:
      service_name: api-gateway