name: CI - notification-service

on:
  push:
    branches: [main]
    paths:
      - 'notification-service/**'

jobs:
  call-build:
    uses: ./.github/workflows/_reusable-build.yaml
    with:
      service_name: notification-service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}